### ISSUE TITLE
[BUG] Incorrect segmentation in FFMpegVideoDecoder when Audio is disabled

### ISSUE THREAD

**Issue by net-cscience-raphael** [vitrivr/vitrivr-engine#119]
# Description
If one disables audio on `FFmpegVideoDecoder` only one `Segment` on each source is emitted.

## Steps To Reproduce
extract two video files with:
```json
      "decoder": {
        "timeWindowMs": "1000",
        "audio": "false"
      },
```
## Environment
 - MS Windows 10, dev #9a4bc2680a52a82fe7f942b6f38b5b7fd0f478b8

**Comment by rahelarnold98** [comment]
After the first segment is emitted, the flags `videoReady` and `audioReady` are set to false. But since `audio = false`, the `audioReady` flag remains false because there are no audio frames to trigger it again. So, no subsequent segments are actually emitted. Even if additional video frames are collected for further segments, the emit() function isn’t triggered.

In dev #de301d75e015992ea5be82fbeff59aba56a0577a, I changed the condition so that it only depends on `videoReady` if `audio = false`.

**Comment by ppanopticon** [comment]
I have changed your change again so that the mechanism works as intended (it was basically copied from the `VideoDecoder` facility).

Can this bug be closed?
