### ISSUE TITLE
Retrievable metadata concept

### ISSUE THREAD

**Issue by rahelarnold98** [vitrivr/vitrivr-engine#41]
Revisit data model design for metadata

**Comment by sauterl** [comment]
Depends on #39 and essentially should be generic to accommodate more than "only" LSC metadata format.

**Comment by ppanopticon** [comment]
Frankly, I'm not quite sure if I understand what the challenges are here. So maybe we can discuss this during our next meeting?

**Comment by sauterl** [comment]
The current draft envisions a struct descriptor whose schema is defined in the schema configuration.
In particular, sub-fields and sub-field types are configured for this type of descriptor in order to provide a structure similar to a table.
This enables a very flexible and generalised approach, based on a configuration which has anyways to be instance-dependent. One — in my opinion acceptable — caveat is that extractors that populate this, let‘s call it `TableDescriptor`, have to be aware of its schema-dependent configuration.
