### ISSUE TITLE
Industry metadata support: EXIF

### ISSUE THREAD

**Issue by sauterl** [vitrivr/vitrivr-engine#60]
Having support for industry standard metadata formats, such as EXIF, should be a priority.

Based on #59 , an extractor should be built which is capable of reading sparse metadata in industry format and write this data as an metadata descriptor.

**Comment by lucaro** [comment]
Maybe just using something like https://github.com/drewnoakes/metadata-extractor.

**Comment by faberf** [comment]
The problem is, that this library maps the raw exif data to its internal type system and does not provide the reverse direction.  I have a working version of exif metadata extraction in VE using this library where I crudely use the string formatting that the library provides and map it to user configured types. This approach, however, will not work together with issue #61 since, for example if the metadata tag has an enum type, we cannot get the raw value anymore.

I am currently looking into the inner workings of the library to see if there is still some way to use it.

**Comment by faberf** [comment]
Ok I found a better approach, using the Directory.getInt(), Directory.getString()... etc. functions

**Comment by lucaro** [comment]
So the actual value is in the 'Description'? Then, I guess for our purposes, either we have a specific purpose of treating a value in a certain way, and then we know its key and can get the type explicitly. Everything else is a string, since we would not know what to do with it anyway.

**Comment by faberf** [comment]
Currently I am using the approach that the user defines what type they are expecting in the field configuration parameters, which may be sufficient if we only ever want to extract a small portion of metadata.

**Comment by lucaro** [comment]
Sounds reasonable.

**Comment by faberf** [comment]
So, following this idea: https://medium.com/@hajriamine/add-custom-metadata-to-image-files-4a493a086a30
I will read the UserComment tag and parse it as a json. These can then be configured using "custom_MYKEY", allowing traditional exif data like datetime to still be configurable with the other prefixes.

**Comment by ppanopticon** [comment]
Done!
