### ISSUE TITLE
Error in `Resetting to invalid mark`  in `VideoDecoder` unsing `InputStream`

### ISSUE THREAD

**Issue by net-cscience-raphael** [vitrivr/vitrivr-engine#72]
The error occurs when loading huge video files (>2GB) with `InputStream` in class `VideoDecoder` .

As a stopgap solution, `InputStream` is replaced with `File`

![image](https://github.com/vitrivr/vitrivr-engine/assets/14836278/a03a51c4-dfe8-45e8-9892-4abc6564ee40)

**Comment by ppanopticon** [comment]
Working with `File` is not feasible. We have use-cases, where there simply is no file since the data comes from some remote source. 

However, as a fix, the `VideoDecoder` now makes a distinction between `FileSource` and any other type of `Source`.

```kotlin
/* Decode video and audio; make distinction between FileSource and other types of sources. */
if (source is FileSource) {
    FFmpegFrameGrabber(source.path.toFile()).use { grabber ->
        decodeFromGrabber(source, sourceRetrievable, grabber, channel)
    }
} else {
    source.newInputStream().use { input ->
        FFmpegFrameGrabber(input).use { grabber ->
            decodeFromGrabber(source, sourceRetrievable, grabber, channel)
        }
    }
}
```

This should address your issue. However, could you please provide me with the vide that caused the issue (e.g., Switch file sender). I might have a look.

**Comment by ppanopticon** [comment]
@net-cscience-raphael Could you please provide me with an example video that triggers this error?

**Comment by net-cscience-raphael** [comment]
https://filesender.switch.ch/filesender2/?s=download&token=c0c10160-3259-41df-8290-593cdd556693
