### ISSUE TITLE
Unify the use of JSON libraries

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#79]
# Task Description

vitrivr engine and its plugins currently rely on various JSON libraries. Namely:

- **kotlinx.serialization:** https://github.com/Kotlin/kotlinx.serialization
- **Moshi:** https://github.com/square/moshi
- **Jackson:** https://github.com/FasterXML/jackson
- **Gson:** https://github.com/google/gson

This clutters the dependency tree and leads to unreasonably large artifacts. The goal of this issue is therefore:

1. To agree on a single JSON library to use.
2. Remove all these dependencies in favour of the one and only.

Personally, I'd be very much in favour of using `kotlinx.serialization` for everything. The following modules / classes are affected by this change:

- Module: `vitrivr-engine-module-fes` (Moshi)
- Class: `CineastMigrationTool` (GSON)
- Class: `ExifMetadataExtractor` (GSON)
- Class: `KotlinxJsonMapper` (Jackson as some sort of fallback)
- Everything related to Javalin and Configuration (kotlinx.serialization)

## Boundary Conditions

Dependencies relying on different JSON libraries can be adjusted or removed (if not needed anymore).

**Comment by sauterl** [comment]
I second the unified usage of `kotlinx.serialization`

**Comment by lucaro** [comment]
I also support the use of kotlinx.serialization. The fallback using Jackson is, however, very deliberate since there are some edge cases that will be very difficult to debug. We can choose to not care about those, which is the cleaner and more consistent way of doing things, but it might lead to nasty issues in the future.

**Comment by faberf** [comment]
Thanks for writing this up. I agree with this and am working on it.

**Comment by faberf** [comment]
@ppanopticon Do you know of a plugin for openapi to generate a kotlin client that uses kotlinx serialization?

**Comment by ppanopticon** [comment]
I'd expect this to be specific to the client / server framework you use (and not Open API itself). In Javalin, for example, you have facilities to provide your own JSON serializer (which we did).

See [`KotlinxJsonMapper`](https://github.com/vitrivr/vitrivr-engine/blob/dev/vitrivr-engine-server/src/main/kotlin/org/vitrivr/engine/server/api/rest/KotlinxJsonMapper.kt)

**Comment by faberf** [comment]
I realised there are a bunch of configurations in the openapi generator https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/kotlin.md that i havent played with yet. This is more relevant when I am dealing with an autogenerated client (not a server)

**Comment by faberf** [comment]
@ppanopticon You mentioned in the meeting that you would quickly write up a guide of how to use kotlinx for collections in the context of the kotlinxjsonmapper. I am currently stuck on this point and would appreciate a quick pointer.

**Comment by lucaro** [comment]
Thanks, @ppanopticon, for the detailed write-up. Maybe as a quick addendum, specifically in the context of APIs: some code generators struggle with generic collections when used as a return type of an API call. It is,, therefore,, preferable to introduce container/wrapper types rather than returning a 'naked' collection. I.e., use something like 
```kotlin
data class AnimalList(val animals: List<Animal>)
```
rather than
```kotlin
Array<Animal>
```
when defining API enpoints.

**Comment by ppanopticon** [comment]
Done!
